# Generated by Django 2.0.7 on 2018-07-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KubePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('labels', models.CharField(max_length=255)),
                ('phase', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
    ]
