# Generated by Django 2.0.7 on 2018-08-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180731_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubemetric',
            name='pod',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='metrics',
                to='api.KubePod'),
        ),
    ]
