# Generated by Django 2.0.7 on 2018-08-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180802_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(
                    choices=[
                        ('started', 'started'),
                        ('failed', 'failed'),
                        ('finished', 'finished')],
                    default='initialized',
                    max_length=20)),
                ('job_id', models.CharField(default='', max_length=38)),
            ],
        ),
        migrations.AlterField(
            model_name='kubemetric',
            name='pod',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='metrics',
                to='api.KubePod'),
        ),
        migrations.AddField(
            model_name='kubemetric',
            name='model_run',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='metrics',
                to='api.ModelRun'),
        ),
    ]
