# Generated by Django 2.0.7 on 2018-08-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_kubepod_model_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
